# Customers Service — manages owner and pet data
# SPCAD-22 | Deploy Services 4–6
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: spring-petclinic-ireland
  labels:
    app: customers-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      initContainers:
        - name: wait-for-discovery-server
          image: busybox
          command: ['sh', '-c', 'until wget -qO- http://discovery-server:8761/actuator/health; do echo waiting for discovery-server; sleep 5; done']
      containers:
        - name: customers-service
          image: 135728714831.dkr.ecr.eu-west-1.amazonaws.com/spring-petclinic-customers-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,mysql"
            - name: CONFIG_SERVER_URL
              value: "http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://spring-petclinic-ireland-mysql.cf2ocuwawblu.eu-west-1.rds.amazonaws.com:3306/petclinic_customers?useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: spring-petclinic-ireland
spec:
  selector:
    app: customers-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
